#baseurl = "http://acsweb.ucsd.edu/~jrorosco/"
baseurl = "https://www.jeremyorosco.info/"
languageCode = "en-us"
title = "Jeremy Orosco"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-90760467-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# Metadata
	name = "Jeremy Orosco"
	description = "This is a personal website for Jeremy Orosco, a Postdoctoral Scholar at UC San Diego."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "me.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Jeremy Orosco**"
		# The icons will be shown if you enter your username
		twitter = ""
		email="jrorosco@eng.ucsd.edu"
		github = "jrorosco"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Jeremy Orosco",
			"Design: [HTML5 UP](//html5up.net)",
			"Workflow: [Netlify](//netlify.com/)"
		]


	[params.about]
		hide  = false
		title = "**Hi, I'm Jeremy.**"
		content = "I'm a Postdoctoral Scholar studying acoustic microfluidics in the [Department of Mechanical and Aerospace Engineering](http://maeweb.ucsd.edu/) at [University of California San Diego](http://ucsd.edu). I received my BS (2014), MS (2016), and PhD (2019) from UCSD. My dissertation research was advised by [Carlos Coimbra](http://jacobsschool.ucsd.edu/faculty/faculty_bios/index.sfe?fmp_recid=324), and was funded by the [San Diego Fellowship](https://grad.ucsd.edu/diversity/incoming-fellowships/sdf-cr-fellowships.html) and the [President's Dissertation Year Fellowship](https://grad.ucsd.edu/financial/fellowships/funding-opportunties/presidents-dissertation-year-fellowship-fletcher-jones.html). During my time with the [Coimbra Research Group](http://coimbra.ucsd.edu/) (CRG) I was involved with a number of research projects such as resource-to-power modeling and high-fidelity forecast generation for large-scale solar power plants, and the development of low-cost, rapidly deployable, self-sustaining [portable weather sensing stations](https://photos.google.com/share/AF1QipNpTO-wg1ZiwnDZPU1G_ZM6gj0-huyLOT3A2zw23cqiHEN935GVEvDb94tqdPFl2Q?key=anBRQm9pblp3dVBNMGl6SVZpWWh3LUs2VjZfUDN3). Sometimes I build robots [[1](https://youtu.be/HZC7KEO-Fjc?t=46), [2](https://www.youtube.com/watch?v=AT6fh77XeX8), [3](https://www.youtube.com/watch?v=z70l3OUy9N4)]. Over the Summer and Fall of 2016, I spent time working on bleeding edge semiconductor chip manufacturing technology at [Cymer/ASML](https://www.cymer.com/).<br><br> Outside of research, I mentor undergraduate students on their journey toward postgraduate study through the [STARS](https://grad.ucsd.edu/diversity/programs/stars/index.html) and [UC LEADS](https://www.ucop.edu/graduate-studies/initiatives-outreach/uc-leads.html) programs. In the past I have also worked with the [IDEA Scholars](http://jacobsschool.ucsd.edu/idea/programs/scholars.shtml) program and with high school outreach through the CRG.<br><br>This is the new address of my [previous site](http://acsweb.ucsd.edu/~jrorosco/)."


	[params.portfolio]
		hide  = false
		title = "My research..."
		content = "... takes place in the space of nonlocal operators and variable order dynamics. My interests include identification, control, and stability; non-convex optimization; and condensed matter systems.<br><br> Currently, my research efforts are directed toward the development of efficient numerical methods for the solution of variable order differential equations and the description of macroscopic emergence in semi-disordered condensed matter systems using generalized differential models."

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]

            # forthcoming
            thumb9 = "thumbs/paper_thumb_9.png"
            title9 = "Simple expression for low-expense approximation of the Bloch-Grüneisen intrinsic resistivity"
            author9 = "J. Orosco and C. F. M. Coimbra"
            journal9 = ""
            year9 = "forthcoming: 75%"
            doi_url9 = "https://www.jeremyorosco.info"
            pdf_url9 = "https://www.jeremyorosco.info"
            bib_url9 = "https://www.jeremyorosco.info"
            description9 = ""

			# International Journal of Heat and Mass Transfer (2019)
			thumb8 = "thumbs/paper_thumb_8.png"
			title8 = "Temperature-dependent infrared optical and radiative properties of platinum"
			author8 = "J. Orosco and C. F. M. Coimbra"
			journal8 = "International Journal of Heat and Mass Transfer"
			year8 = "2019"
			doi_url8 = "https://doi.org/10.1016/j.ijheatmasstransfer.2019.118471"
			pdf_url8 = "files/2019c_Orosco_Coimbra.pdf"
			bib_url8 = "files/2019c_Orosco_Coimbra.bib"
			description8 = "A temperature-dependent Gauss-Lorentz interband oscillator is defined and combined with a previously proposed temperature-dependent anomalous intraband component in order to arrive at a spectral thermophysical model for the infrared optical and radiative properties of platinum. Validation is obtained in terms of the Planck-weighted radiative properties."

			# Journal of Applied Physics (2019)
			thumb7 = "thumbs/paper_thumb_7.png"
			title7 = "Temperature-dependent carrier transport: Low-complexity model for the infrared optical and radiative properties of nickel"
			author7 = "J. Orosco and C. F. M. Coimbra"
			journal7 = "Journal of Applied Physics"
			year7 = "2019"
			doi_url7 = "https://doi.org/10.1063/1.5091792"
			pdf_url7 = "files/2019b_Orosco_Coimbra.pdf"
			bib_url7 = "files/2019b_Orosco_Coimbra.bib"
			description7 = "Earlier preliminary model development is refined and expanded. A systematic procedure is described for deriving model parameters from data. The model and procedure provide a means for inverse estimation of the smooth complex optical indices at higher temperatures. Results and validation are provided for elemental nickel."

			# AIAA's SciTech Forum (2019)
			thumb6 = "thumbs/paper_thumb_6.png"
			title6 = "Thermophysical model for the infrared emissivity of metals"
			author6 = "J. Orosco and C. F. M. Coimbra"
			journal6 = "AIAA SciTech Forum: Paper and Presentation"
			year6 = "2019"
			doi_url6 = "https://doi.org/10.2514/6.2019-1280"
			pdf_url6 = "files/2019a_Orosco_Coimbra.pdf"
			bib_url6 = "files/2019a_Orosco_Coimbra.bib"
            slides_url6 = "files/2019a_Orosco_Coimbra_slides.pdf"
			description6 = "A spectral thermophysical model is derived for the infrared optical and radiative properties of metals possessing complex valency. The response equations are formulated on the basis of anomalous carrier transport with thermal dependence established by the solution to the BTE in the RTA. Preliminary results are presented for application to nickel."

			# Physical Review B (2018)
			thumb5 = "thumbs/paper_thumb_5.png"
			title5 = "Anomalous carrier transport model for broadband infrared absorption in metals"
			author5 = "J. Orosco and C. F. M. Coimbra"
			journal5 = "Physical Review B"
			year5 = "2018"
			doi_url5 = "https://doi.org/10.1103/PhysRevB.98.235118"
			pdf_url5 = "files/2018d_Orosco_Coimbra.pdf"
			bib_url5 = "files/2018d_Orosco_Coimbra.bib"
			description5 = "A robust, high-fidelity model is derived for correlating measurements of the broadband infrared optical response of metals. Anomalous dynamics are introduced as a correction to the local field that accounts for diffusive perturbations subscribing to a non-Markovian relaxation. Examples are given for several metals of engineering significance."

			# Physical Review E (2018)
			thumb4 = "thumbs/paper_thumb_4.png"
			title4 = "Variable-order modeling of nonlocal emergence in many-body systems: Application to radiative dispersion"
			author4 = "J. Orosco and C. F. M. Coimbra"
			journal4 = "Physical Review E"
			year4 = "2018"
			doi_url4 = "https://doi.org/10.1103/PhysRevE.98.032208"
			pdf_url4 = "files/2018c_Orosco_Coimbra.pdf"
			bib_url4 = "files/2018c_Orosco_Coimbra.bib"
			description4 = "A generalized spectroscopic analysis framework is derived within the formalism of variable-order calculus. The framework is applied for analysis and modeling of emergent temporally nonlocal effects in many-body condensed matter systems. A sample application is demonstrated. Validation is obtained in a multi-objective (optical and radiative) setting."

			# Applied Optics (2018)
			thumb3 = "thumbs/paper_thumb_3.png"
			title3 = "On a causal dispersion model for the optical properties of metals"
			author3 = "J. Orosco and C. F. M. Coimbra"
			journal3 = "Applied Optics"
			year3 = 2018
			doi_url3 = "https://doi.org/10.1364/AO.57.005333"
			pdf_url3 = "files/2018b_Orosco_Coimbra.pdf"
			bib_url3 = "files/2018b_Orosco_Coimbra.bib"
			description3 = "A KKR-compliant model with tunable Gaussian-Lorentzian character is proposed for interband electron dynamics. Optimal regression of the model from complex-valued data is achieved using a novel reductive procedure. Validation performed for eleven metals demonstrates a significant improvement over previously proposed, KKR-noncompliant models."

			# Physical Review B (2018)
			thumb2 = "thumbs/paper_thumb_2.png"
			title2 = "Optical response of thin amorphous films to infrared radiation"
			author2 = "J. Orosco and C. F. M. Coimbra"
			journal2 = "Physical Review B"
			year2 = 2018
			doi_url2 = "https://doi.org/10.1103/PhysRevB.97.094301"
			pdf_url2 = "files/2018a_Orosco_Coimbra.pdf"
			bib_url2 = "files/2018a_Orosco_Coimbra.bib"
			description2 = "A Kramers-Kronig consistent model is proposed for the relative permittivity of dielectric solids. The model accurately reproduces the convolved Gaussian-Lorentzian absorption peaks observed in the optical response of amorphous media. Results indicate a performance commensurate with previously proposed, KKR-noncompliant models."

			# Nonlinear Dynamics (2016)
			thumb1 = "thumbs/paper_thumb_1.png"
			title1 = "On the control and stability of variable-order mechanical systems"
			author1 = "J. Orosco and C. F. M. Coimbra"
			journal1 = "Nonlinear Dynamics"
			year1 = 2016
			doi_url1 = "https://doi.org/10.1007/s11071-016-2916-9"
			pdf_url1 = "files/2016_Orosco_Coimbra.pdf"
			bib_url1 = "files/2016_Orosco_Coimbra.bib"
			description1 = "Modern control methods are extended for use with a nonlinear system of variable-order differential equations. An analytical expression is derived for the dependence of the closed-loop stability on the variable order damping. Numerical simulations demonstrate the efficacy of the control solution and confirm the predictive validity of the stability equation."

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.rss]
		hide = true

	[params.contact]
		hide  = false
		title = "Get in touch."
		content = "Say hi, ask a question, inquire about collaboration, or just ponder philosophically..."

		#address = [
		#	"1234 Somewhere Rd.",
		#	"Nashville, TN 00000",
		#	"United States"
		#]
		#phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "jrorosco@eng.ucsd.edu"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "cv"
	url  = "files/jeremy_orosco.pdf"
	weight = 10

[[menu.main]]
	name = "email"
	url = ""
	weight = 20

[[menu.main]]
	name = "sms"
	url="mailto:sms@jeremyorosco.info"
	weight = 30

#[[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 10
